### PR TITLE
Xcode Bot Support

### PR DESCRIPTION
**Pull request by travisbader**
Hello

Thanks for this awesome project!  I have used CCMenu for years and love it!  In that time we have moved from CCNet to Jenkins and now to Xcode Bots.  I really missed CCMenu support when I moved to Bots so I decided to implement support for it!

I was hoping this feature could be pulled in.

Thanks!
Travis

### CODE REVIEW

**Comment by erikdoe** [comment]
Just as a heads up. I'm not ignoring this, but I haven't found the time I need to spend with this.

Also, is there a demo setup I can use? Is there a simple to follow tutorial to create a demo setup? I have a fair amount of experience with CI/CD servers but I have never used Xcode bots.

**Comment by o2x7** [comment]
Erik

Thanks for the heads up.  I so wish Apple did provide a sample server, but it is Apple after all!  Our servers are all behind firewalls so I can’t give you access there.  Probably the best tutorial i have found is here:

https://honzadvorsky.com/articles/2015-08-04-xcs_tutorials_1_getting_started/ <https://honzadvorsky.com/articles/2015-08-04-xcs_tutorials_1_getting_started/>

Thanks again!
Travis

**Comment by o2x7** [comment]
I guess I should give you apple’s guide as well… 

https://developer.apple.com/library/content/documentation/IDEs/Conceptual/xcode_guide-continuous_integration/adopt_continuous_integration.html#//apple_ref/doc/uid/TP40013292-CH3-SW1 <https://developer.apple.com/library/content/documentation/IDEs/Conceptual/xcode_guide-continuous_integration/adopt_continuous_integration.html#//apple_ref/doc/uid/TP40013292-CH3-SW1>

**Comment by erikdoe** [comment]
This version of CCMenu is retired. The new version may get support for Xcode Bots.

**Pull request closed without merging**
