### PR TITLE
Enlarged add job window horizontally

### LINKED ISSUE #80: Feed URL dropdown is too short hiding critical information
The current server dropdown is not wide enough and prevents the user from picking the right URL.

This is a real issue on instances using folders where you need to use different URLs on the same host, making the re-use of server url a real challenge.

monosnap 2017-03-27 15-14-54

It seems that the shortener algorithm needs to be updated because cutting the last part is not the best idea.

Note: I think that making it even 50% wider it will not solve the problem from this case. As you can see the current width is not enough to fit even the domain name.

### PR DESCRIPTION
**Pull request by ssbarnea**
Fixes #80 and below you can see the new window layout:

ccmenu-resize-2
ccmenu-resize-1

### CODE REVIEW

**Comment by ssbarnea** [comment]
@erikdoe If you could have a look at this it would be great. 

As you can observe there are few other side effects of editing the project with a newer version of XCode. Still, these added xml properties should not affect use of older versions of XCode.

**Comment by jacksonjesse** [comment]
I'm not particularly qualified as a Mac OS developer so hard for me to understand the exact change, but to clarify, is this just making the window a wider fixed width, or actually allowing the window to be made wider?

**Comment by ssbarnea** [comment]
@jacksonjesse Is not making it resizable as I don't know exactly how to do this myself. Still, it does enlarge it to the size you see on the screenshot, which is only a little bit bigger than the main config
window.

This is the the safest approach as it would avoid making it bigger than then the narrowest monitor.

I hope @erikdoe will merge this sooner and make a new release as is really painful to have to run my own build just to be able to use ccmenu.

TBH, I don't care if this is merges as is or if he decides to make a similar change directly and push it as long it goes ccmenu. The current width are just far too small.

**Comment by erikdoe** [comment]
I've just made a commit that makes the sheet resizable (fbe881b08b8c5c48e1ce23a01c004922c036beac). Can you double-check that this works for you?

In a second commit I've also changed the truncating mode to "middle", meaning thatlong project names will be shortened in the middle, keeping the last part visible. Is that helpful?

**Comment by jacksonjesse** [comment]
Yep quick tests suggests this is exactly what I'm after!

**Comment by ssbarnea** [comment]
@erikdoe Thanks for doing that! Yes, resize works well and also middle-trunction mode. 

On the other hand I found a bug that I didn't see so far, clearly unrelated to those changes. https://github.com/erikdoe/ccmenu/issues/99

**Pull request closed without merging**
