### PR TITLE
Update icons

### PR DESCRIPTION
**Pull request by fabian**
Modern icons based on [Ionicons](http://ionicons.com).

     

By using an _Asset catalog folder_ I was also able to remove some old hacks for Retina. That's now handled by the system.

I also added an option to disable the colored icons and use black and white ones instead (using the alpha channel). This is especially useful when using the black menu bar.

Source file for the icons is `Images.sketch` which can be opened with [Sketch](http://www.sketchapp.com) if needed.

### CODE REVIEW

**Comment by fabian** [comment]
Would probably also solve #34.

**Comment by dapi** [comment]
nice

**Comment by erikdoe** [comment]
This does look pretty good and I was hoping to have it merged already. Unfortunately, there was a problem in the App Store review process for the previous version which meant I had to touch the project and XIB files, resulting in merge conflicts for this PR as is. Do you think it would be possible to update this PR to the latest in master?

**Comment by fabian** [comment]
Sure, just rebased the PR.

As for the `convertFor*`methods, I assume their original purpose was to do some resizing and moving of the icons? This should not be needed anymore with the new images as they work in both the menu and the dropdown with the correct sizes.

**Comment by erikdoe** [comment]
Thanks for the quick response. Once the bugfix release for El Capitan (see #33) has made it into the App Store, I'll merge this into master.

**Comment by thomas-mann** [comment]
Looks nice. I would love to see some b/w icons. I will create a pull request with the b/w icons and maybe a setting. @erikdoe What do you think?

**Comment by fabian** [comment]
@thomas-mann B/W icons are already included in this PR. There's an option in the preferences window to enable them. They simply use the alpha channel of the color icons.

**Comment by erikdoe** [comment]
Now that the bugs in 1.10 are fixed and released in the app store this PR is next on the list.

**Comment by thomas-mann** [comment]
@fabian and @erikdoe great!

**Comment by erikdoe** [comment]
I have merged this PR but Github doesn't recognise it. Will close manually.

By the way, I had to revert the removal of the conversion methods because the images were not aligned quite right in the menu without adjustment. Notice how the icon is displayed a bit too high up in the menu?

screen shot 2015-11-18 at 12 25 27

Given the size and visibility of the contribution I'd like to mention you in the about panel. Do you have any concerns?

**Comment by fabian** [comment]
Thanks!

Yes I can see the problem with the icon alignment in the menu now - it even seems to be a problem of the system, I can also see it in Safari.

screenshot 2015-11-20 09 49 41 2

But yes, good to have a fix for it then.

Sure, I'm happy to be listed as contributor!

**Pull request closed without merging**
